
name: "CI (Integração Continua): Primeira Action"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Ativa esse fluxo de trabalho para cada push ou pull que acontecer apoontando para a branch "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Definindo o que queremos executar
jobs:
    exemplo: #Job: exemplo
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Run a one-line script
              run: echo Hello, world!


