name: "CI (Integração Continua): Main Workflow"

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run linter: github-actions-cicd"
        run: cd github-actions-cicd && yarn lint