name: "CI (Integração Continua): Main Workflow"

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3
      - name: Change diretory
        run: cd github-actions-cicd
      - name: Run linter
        run: yarn lint